//! `tension::audio` — the second Tension host service.
//!
//! TensionCore is a coprocessor model: the guest is the CPU, the host is
//! the substrate, and every guest capability that cannot be implemented in
//! wasm is a SERVICE reached through a command protocol. `tension::io` is
//! the first service (synchronous, stateless, terminal). `tension::audio`
//! is the first STATEFUL service: it has a lifecycle (init / verbs /
//! shutdown) and a driver thread that keeps moving without the guest
//! calling into it.
//!
//! # Low level by design
//!
//! The host is a PCM sink, not a synthesiser. It does not know what a
//! "sine" or a "square" is. It knows how to: open a device, accept a
//! buffer of mono `f32` PCM from the guest, play it (optionally looping and
//! resampled to the device rate), change its gain, stop it, and report
//! whether a voice handle is still live. Everything about *what to play* —
//! waveform, frequency, duration — is generated by the guest and handed
//! over as samples.
//!
//! # Contract
//!
//!   audio_init(sample_rate, channels) -> i32   0 ok, -1 err; first-wins
//!   audio_play(ptr, len, rate, gain, loop) -> i32
//!       ptr/len: mono f32 PCM in guest memory (little-endian); rate: the
//!       PCM's sample rate. Returns an opaque voice handle, or -1.
//!   audio_stop(voice) -> i32       0 if live, -1 otherwise
//!   audio_set_gain(voice, gain) -> i32   gain clamped to [0,1]
//!   audio_voice_state(voice) -> i32      1 live, 0 dead, -1 never allocated
//!   audio_shutdown() -> i32             stop everything; idempotent
//!
//! Handles are opaque `i32`. A handle is valid only while the voice it
//! names is alive; validity is checked host-side, and the guest must not
//! interpret or perform arithmetic on a handle. The encoding is
//! adapter-internal.
//!
//! All six verbs run on the guest thread. `audio_init` and `audio_shutdown`
//! may block (bounded); `play` / `stop` / `set_gain` / `voice_state` do not.
//! `audio_init` is first-wins: a second call with different params returns
//! 0 and is ignored; the session's params are fixed at first successful
//! init until `audio_shutdown`.
//!
//! This module owns the shared contract — init gate, param validation, gain
//! clamping, shutdown idempotence — so no adapter can diverge on it. The
//! adapters (`headless`, `real`) own only their mechanics.

use wasmtime::{Caller, Linker};

use crate::HostState;

/// Headless adapter: renders the guest's PCM to a WAV file. The no-feature
/// fallback and the test adapter.
#[cfg(any(not(feature = "audio"), test))]
pub mod headless;
/// Device-backed adapter (cpal): plays the guest's PCM through the system
/// sound device.
#[cfg(feature = "audio")]
pub mod real;

/// Maximum number of concurrently live voices.
pub const MAX_VOICES: usize = 32;

/// What any audio adapter must do. The `AudioSession` gate layer above owns
/// the shared contract and calls these only with validated arguments.
pub trait AudioAdapter {
    /// Open the device / start the session. Only called on first successful
    /// init; the gate guarantees validated params.
    fn do_init(&mut self, sample_rate: i32, channels: i32) -> i32;
    /// Start a voice playing the given mono PCM. `rate` is the PCM's sample
    /// rate; `gain` is already clamped. Returns an opaque handle, or -1.
    fn do_play(&mut self, pcm: &[f32], rate: i32, gain: f32, loop_: bool) -> i32;
    /// Stop a live voice. 0 if it was live, -1 otherwise.
    fn do_stop(&mut self, voice: i32) -> i32;
    /// Set the gain of a live voice. 0 if it was live, -1 otherwise.
    fn do_set_gain(&mut self, voice: i32, gain: f32) -> i32;
    /// 1 live, 0 dead but known, -1 never allocated.
    fn voice_state(&mut self, voice: i32) -> i32;
    /// Stop everything and release adapter state. Idempotent.
    fn do_shutdown(&mut self) -> i32;
}

/// The session gate layer: holds the adapter and enforces the shared
/// contract on every call before (and after) delegating.
pub struct AudioSession {
    adapter: Box<dyn AudioAdapter>,
    initialized: bool,
}

impl AudioSession {
    pub fn new(adapter: Box<dyn AudioAdapter>) -> Self {
        Self { adapter, initialized: false }
    }

    pub fn init(&mut self, sample_rate: i32, channels: i32) -> i32 {
        let ret;
        if self.initialized {
            // first-wins: params are fixed at first successful init.
            ret = 0;
        } else if sample_rate <= 0 || (channels != 1 && channels != 2) {
            ret = -1;
        } else {
            ret = self.adapter.do_init(sample_rate, channels);
            if ret == 0 {
                self.initialized = true;
            }
        }
        log(&format!("audio_init(sample_rate={sample_rate}, channels={channels}) -> {ret}"));
        ret
    }

    pub fn play(&mut self, pcm: &[f32], rate: i32, gain: f32, loop_: bool) -> i32 {
        let ret;
        if !self.initialized {
            ret = -1;
        } else if rate <= 0 || pcm.is_empty() {
            ret = -1;
        } else {
            ret = self.adapter.do_play(pcm, rate, clamp_gain(gain), loop_);
        }
        log(&format!(
            "audio_play(len={}, rate={rate}, gain={gain:.2}, loop={loop_}) -> {ret}",
            pcm.len()
        ));
        ret
    }

    pub fn stop(&mut self, voice: i32) -> i32 {
        let ret = if self.initialized { self.adapter.do_stop(voice) } else { -1 };
        log(&format!("audio_stop(voice={voice}) -> {ret}"));
        ret
    }

    pub fn set_gain(&mut self, voice: i32, gain: f32) -> i32 {
        let ret = if self.initialized {
            self.adapter.do_set_gain(voice, clamp_gain(gain))
        } else {
            -1
        };
        log(&format!("audio_set_gain(voice={voice}, gain={gain:.2}) -> {ret}"));
        ret
    }

    pub fn voice_state(&mut self, voice: i32) -> i32 {
        let ret = if self.initialized { self.adapter.voice_state(voice) } else { -1 };
        log(&format!("audio_voice_state(voice={voice}) -> {ret}"));
        ret
    }

    pub fn shutdown(&mut self) -> i32 {
        self.adapter.do_shutdown();
        self.initialized = false;
        log("audio_shutdown() -> 0");
        0
    }
}

/// Read `len` bytes at `ptr` from guest memory and parse them as little-
/// endian `f32` samples (clamped to the memory bounds; non-finite samples
/// are coerced to 0.0 so a bad buffer can never poison the mixer).
fn read_pcm(caller: &mut Caller<'_, HostState>, ptr: i32, len: i32) -> Vec<f32> {
    let mut pcm = Vec::new();
    if ptr <= 0 || len <= 0 {
        return pcm;
    }
    let Some(mem) = caller.get_export("memory").and_then(|e| e.into_memory()) else {
        return pcm;
    };
    let data = mem.data(&*caller);
    let start = (ptr as usize).min(data.len());
    let end = start.saturating_add(len as usize).min(data.len());
    let bytes = &data[start..end];
    pcm.reserve(bytes.len() / 4);
    for chunk in bytes.chunks_exact(4) {
        let v = f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
        pcm.push(if v.is_finite() { v } else { 0.0 });
    }
    pcm
}

/// Register the six `tension::audio` imports. `tension::io` is untouched.
pub fn link_audio(linker: &mut Linker<HostState>) -> anyhow::Result<()> {
    linker.func_wrap(
        "tension::audio",
        "audio_init",
        |mut caller: Caller<'_, HostState>, sample_rate: i32, channels: i32| -> i32 {
            caller.data_mut().audio.init(sample_rate, channels)
        },
    )?;

    linker.func_wrap(
        "tension::audio",
        "audio_play",
        |mut caller: Caller<'_, HostState>, ptr: i32, len: i32, rate: i32, gain: f32, loop_: i32| -> i32 {
            let pcm = read_pcm(&mut caller, ptr, len);
            caller.data_mut().audio.play(&pcm, rate, gain, loop_ != 0)
        },
    )?;

    linker.func_wrap(
        "tension::audio",
        "audio_stop",
        |mut caller: Caller<'_, HostState>, voice: i32| -> i32 {
            caller.data_mut().audio.stop(voice)
        },
    )?;

    linker.func_wrap(
        "tension::audio",
        "audio_set_gain",
        |mut caller: Caller<'_, HostState>, voice: i32, gain: f32| -> i32 {
            caller.data_mut().audio.set_gain(voice, gain)
        },
    )?;

    linker.func_wrap(
        "tension::audio",
        "audio_voice_state",
        |mut caller: Caller<'_, HostState>, voice: i32| -> i32 {
            caller.data_mut().audio.voice_state(voice)
        },
    )?;

    linker.func_wrap(
        "tension::audio",
        "audio_shutdown",
        |mut caller: Caller<'_, HostState>| -> i32 {
            caller.data_mut().audio.shutdown()
        },
    )?;

    Ok(())
}

/// Clamp gain to [0, 1]; non-finite values (NaN, ±inf) become 0.0.
/// (`f32::clamp` passes NaN through, hence the explicit check.)
fn clamp_gain(gain: f32) -> f32 {
    if !gain.is_finite() {
        0.0
    } else {
        gain.clamp(0.0, 1.0)
    }
}

/// One line per verb call on stderr: `[tension:audio] <verb>(<args>) -> <ret>`.
fn log(call: &str) {
    eprintln!("[tension:audio] {call}");
}
