// Generated by tension-framework/build.sh from session.json — do not edit.
//
// The arena constants this guest is compiled against: what it sends in the
// session TLV, and the layout hash the session compares against its own. The
// Rust side's `arena::layout_hash()` is the authority for the hash; the
// cross-check test in tension-core reads this file and fails loudly if the two
// ever disagree.
//
// Memory flags this file implies (also generated, as an asconfig):
//   --importMemory --memoryBase 8388608 \
//   --initialMemory 132 --maximumMemory 512 \
//   --exportTable --runtime stub
// `--noExportMemory` is forbidden (F2) and `--lowMemoryLimit` likewise.

export const ABI_VERSION: u32 = 1;
export const LAYOUT_HASH: u32 = 3451714980;
/** The live arena this guest asks for (bytes). */
export const ARENA_SIZE: u32 = 6250528;
/** The ceiling, and therefore the guest's `--memoryBase`. */
export const MAX_ARENA_SIZE: u32 = 8388608;
export const MEMORY_BASE: u32 = 8388608;
export const INITIAL_PAGES: u32 = 132;
export const MAXIMUM_PAGES: u32 = 512;
export const CLASS_COUNT: u32 = 10;
/** Per-class ring capacities, in class-id order. */
export const RING_CAPACITIES: u32[] = [1, 256, 256, 64, 4096, 4096, 256, 64, 1024, 256];
