#!/usr/bin/env bash
# Pack the example's asset tree into a pak with the Zig packer.
#
# The tree that gets packed is assembled in a temp dir rather than taken from
# assets/ directly: one File (data/large.bin, ~20 MiB) is too big to commit, so
# it is generated here at pack time and copied in. The committed assets/
# directory is never written to.
#
# The generated source is left at build/large.bin (a scratch path — see the
# repository .gitignore) so verify.sh can compare the bytes read back out of
# the pak against the bytes that went in.
#
# Determinism: the generated bytes are a pure function of the size — bytes
# 0..63 repeated — so the pak is byte-reproducible from source, and packing
# twice produces identical volumes (verify.sh step 3).
#
# Usage: pack.sh [output.tns]   (default: game.tns next to this script)
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
packer="${TENSION_PACK:-$here/../../tension-res/zig-out/bin/tension-pack}"
large_bytes="${TENSION_LARGE_BYTES:-20971520}"       # 20 MiB: incompressible, stays stored
compressible_bytes="${TENSION_COMPRESSIBLE_BYTES:-2097152}" # 2 MiB of zeros: compresses
out="${1:-$here/game.tns}"

mkdir -p "$here/build"
python3 - "$here/build/large.bin" "$large_bytes" "$here/build/compressed.bin" "$compressible_bytes" <<'PY'
import sys

large_path, large_size, comp_path, comp_size = (
    sys.argv[1], int(sys.argv[2]), sys.argv[3], int(sys.argv[4]),
)


def pattern_byte(o):
    # A deterministic keystream, bit-exact with the demo's. It must not be
    # compressible: this File exists to span more chunks than the runtime's
    # per-open cache holds, and a repeating pattern would collapse under the
    # packer's compression threshold and end that coverage.
    x = (o * 747796405 + 2891336453) & 0xFFFFFFFF
    x ^= x >> 15
    x = (x * 2246822519) & 0xFFFFFFFF
    x ^= x >> 13
    return x & 0xFF


with open(large_path, "wb") as fh:
    # Evaluate the mixer at the *absolute* offset: a repeated block would be
    # periodic (and compressible) while the demo checks pattern_byte(o) for the
    # real file offset o.
    step = 1 << 16
    written = 0
    while written < large_size:
        n = min(step, large_size - written)
        fh.write(bytes(pattern_byte(written + k) for k in range(n)))
        written += n

# 2 MiB of zeros: highly compressible, and small enough after compression that
# the wrapped File still fits the runtime's chunk cache, so its reads are cheap.
with open(comp_path, "wb") as fh:
    zero = bytes(1 << 16)
    written = 0
    while written < comp_size:
        chunk = min(len(zero), comp_size - written)
        fh.write(zero[:chunk])
        written += chunk
PY

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$tmp/assets"
cp -R "$here/assets/." "$tmp/assets/"
cp "$here/build/large.bin" "$tmp/assets/data/large.bin"
cp "$here/build/compressed.bin" "$tmp/assets/data/compressed.bin"

"$packer" "$tmp/assets" -o "$out" -v
printf 'large.bin: %s bytes generated (incompressible keystream)\n' "$large_bytes"
printf 'compressed.bin: %s bytes generated (zeros)\n' "$compressible_bytes"
