// The expectations the parser test asserts, read off the format's own runtime.
//
// Generated by `gen-expectations.py` from the output of a C++ tool in /tmp that
// links ozz-animation's runtime (0.17.0) and loads each fixture pair directly:
// Compatible with ozz-animation's runtime archive format (MIT,
// github.com/guillaumeblanc/ozz-animation). That names the format, not this code.
//
// The header facts come from the format's accessors, and the decoded keys come from a
// scalar half->float and quaternion unpack that the tool cross-checks against
// reference sampling job run at the same ratio (it agrees exactly for halfs, and
// to ~5e-6 for quaternions -- the reference decoder uses an estimated reciprocal
// square root there, and this parser uses an exact one).
//
// The tool is not committed; this file is. Regenerating it means rebuilding that
// tool against the same library version. Nothing here is hand-edited.


/** A skeleton archive's expectations, straight from the format's accessors. */
export class SkeletonExpect {
  jointCount: i32 = 0;
  /** `Align(jointCount, 4)`, the number of slots the key arrays would cover. */
  slots: i32 = 0;
  bytes: i32 = 0;
  /** The first five parent indices; -1 is a root. */
  parents: i32[] = [];
  /** The first three joint names. */
  names: string[] = [];
  /** The rest pose of joints 0 and 1: tx, ty, tz, rx, ry, rz, rw, sx, sy, sz. */
  rest: f32[][] = [];
}

/** One key as the archive stores it, and as this parser must decode it. */
export class KeyExpect {
  /** The key's index in the series' key array. The format's sort rule puts a
   * slot's first key at index `slot` and its second at `slot + slots`, so for
   * track 0 these are 0 and `slots` -- an assertion worth making on its own. */
  index: i32 = 0;
  ratio: f32 = 0;
  raw0: u16 = 0;
  raw1: u16 = 0;
  raw2: u16 = 0;
  /** Three values for a translation or a scale; four (a quaternion) for a rotation. */
  value: f32[] = [];
}

/** One series' key count, and the first two keys of track 0. */
export class SeriesExpect {
  /** The series' total key count, from the archive's header. */
  keyCount: i32 = 0;
  /** How many of those keys belong to track 0: the walk's answer, and the one a
   * parser that trusts the track count instead of the slot count gets wrong as
   * soon as the rig is padded. */
  track0KeyCount: i32 = 0;
  keys: KeyExpect[] = [];
}

/** One fixture pair: the two fixture names, and what each must parse to. */
export class FixturePair {
  label: string = "";
  skeleton: string = "";
  animation: string = "";
  skeletonExpect: SkeletonExpect = new SkeletonExpect();
  animationExpect: AnimationExpect = new AnimationExpect();
}

function pair(
  label: string,
  skeleton: string,
  animation: string,
  skeletonExpect: SkeletonExpect,
  animationExpect: AnimationExpect,
): FixturePair {
  const out = new FixturePair();
  out.label = label;
  out.skeleton = skeleton;
  out.animation = animation;
  out.skeletonExpect = skeletonExpect;
  out.animationExpect = animationExpect;
  return out;
}

/** An animation archive's expectations. */
export class AnimationExpect {
  name: string = "";
  duration: f32 = 0;
  trackCount: i32 = 0;
  /** `Align(trackCount, 4)`: more than `trackCount` whenever the rig is padded. */
  slots: i32 = 0;
  timepoints: i32 = 0;
  /** Bytes per ratio field: 1, or 2 when there are more than 255 timepoints. */
  ratioWidth: i32 = 1;
  bytes: i32 = 0;
  translations: SeriesExpect = new SeriesExpect();
  rotations: SeriesExpect = new SeriesExpect();
  scales: SeriesExpect = new SeriesExpect();
}

function key(index: i32, ratio: f32, raw0: u16, raw1: u16, raw2: u16, value: f32[]): KeyExpect {
  const out = new KeyExpect();
  out.index = index;
  out.ratio = ratio;
  out.raw0 = raw0;
  out.raw1 = raw1;
  out.raw2 = raw2;
  out.value = value;
  return out;
}

function series(keyCount: i32, track0KeyCount: i32, keys: KeyExpect[]): SeriesExpect {
  const out = new SeriesExpect();
  out.keyCount = keyCount;
  out.track0KeyCount = track0KeyCount;
  out.keys = keys;
  return out;
}

function skeletonExpect(
  jointCount: i32,
  slots: i32,
  bytes: i32,
  parents: i32[],
  names: string[],
  rest: f32[][],
): SkeletonExpect {
  const out = new SkeletonExpect();
  out.jointCount = jointCount;
  out.slots = slots;
  out.bytes = bytes;
  out.parents = parents;
  out.names = names;
  out.rest = rest;
  return out;
}

function animationExpect(
  name: string,
  duration: f32,
  trackCount: i32,
  slots: i32,
  timepoints: i32,
  ratioWidth: i32,
  bytes: i32,
  translations: SeriesExpect,
  rotations: SeriesExpect,
  scales: SeriesExpect,
): AnimationExpect {
  const out = new AnimationExpect();
  out.name = name;
  out.duration = duration;
  out.trackCount = trackCount;
  out.slots = slots;
  out.timepoints = timepoints;
  out.ratioWidth = ratioWidth;
  out.bytes = bytes;
  out.translations = translations;
  out.rotations = rotations;
  out.scales = scales;
  return out;
}


// --- 1. skeleton_v2_le -------------------------------------
export const FIXTURE_0_SKELETON = skeletonExpect(
  67, 68, 3818,
  <i32[]>[-1, 0, 1, 2, 3],
  <string[]>["Hips", "Pelvis", "Spine"],
  <f32[][]>[
    <f32[]>[-4.01047945e-10, 1.0466696, -0.0151103791, -0.5, -0.5, -0.5, 0.5, 1, 1, 1],
    <f32[]>[0, 0, 0, -0.499999702, -0.500000358, -0.499999702, 0.500000358, 1, 1, 1],
  ],
);
export const FIXTURE_0_ANIMATION = animationExpect(
  "run", <f32>0.666666687, 67, 68,
  21, 1, 7219,
  series(184, 19, [
    key(0, <f32>0.0, 9393, 15255, 43452, <f32[]>[0.0183258057, 0.948730469, -0.0447998047]),
    key(68, <f32>0.0500000045, 9680, 15215, 12051, <f32[]>[0.0227050781, 0.929199219, 0.110534668]),
  ]),
  series(440, 21, [
    key(0, <f32>0.0, 30243, 24004, 11846, <f32[]>[-0.543963134, -0.448105484, -0.451471925, 0.547246397]),
    key(68, <f32>0.0500000045, 27979, 25236, 12536, <f32[]>[-0.556177318, -0.434812278, -0.43658185, 0.557674944]),
  ]),
  series(136, 2, [
    key(0, <f32>0.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
    key(68, <f32>1.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
  ]),
);


// --- 2. robot_skeleton -------------------------------------
export const FIXTURE_1_SKELETON = skeletonExpect(
  18, 20, 986,
  <i32[]>[-1, 0, 1, 2, 3],
  <string[]>["base", "shoulder", "arm_l0"],
  <f32[][]>[
    <f32[]>[0, 0, 0, -0, -0.707106829, 0, 0.707106829, 1, 1, 1],
    <f32[]>[0, 0.099999994, 0, 0, 0, 0.650655448, 0.759373248, 1, 1, 1],
  ],
);
export const FIXTURE_1_ANIMATION = animationExpect(
  "Take 001", <f32>14.666667, 18, 20,
  382, 2, 12009,
  series(40, 2, [
    key(0, <f32>0.0, 0, 0, 0, <f32[]>[0, 0, 0]),
    key(20, <f32>1.0, 0, 0, 0, <f32[]>[0, 0, 0]),
  ]),
  series(955, 52, [
    key(0, <f32>0.0, 65533, 65533, 65534, <f32[]>[-2.15768814e-05, -0.707106769, -2.15768814e-05, 0.707106769]),
    key(20, <f32>0.284090936, 65533, 65533, 65534, <f32[]>[-2.15768814e-05, -0.707106769, -2.15768814e-05, 0.707106769]),
  ]),
  series(40, 2, [
    key(0, <f32>0.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
    key(20, <f32>1.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
  ]),
);


// --- 3. rigged_simple_skeleton -------------------------------------
export const FIXTURE_2_SKELETON = skeletonExpect(
  2, 4, 204,
  <i32[]>[-1, 0],
  <string[]>["Bone", "Bone.001"],
  <f32[][]>[
    <f32[]>[0, -1.35972996e-07, -4.1803298, 0, 0, 0, 1, 1, 1, 1],
    <f32[]>[1.21502999e-11, 0.0279774703, 4.18707705, -0, 0.000289922551, -0, -1, 1, 1, 1],
  ],
);
export const FIXTURE_2_ANIMATION = animationExpect(
  "animation_0", <f32>2.08333302, 2, 4,
  4, 1, 357,
  series(8, 2, [
    key(0, <f32>0.0, 0, 0, 0, <f32[]>[0, 0, 0]),
    key(4, <f32>1.0, 0, 0, 0, <f32[]>[0, 0, 0]),
  ]),
  series(10, 2, [
    key(0, <f32>0.0, 65531, 65533, 32766, <f32[]>[-2.15768814e-05, -2.15768814e-05, -2.15768814e-05, 1]),
    key(4, <f32>1.0, 65531, 65533, 32766, <f32[]>[-2.15768814e-05, -2.15768814e-05, -2.15768814e-05, 1]),
  ]),
  series(8, 2, [
    key(0, <f32>0.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
    key(4, <f32>1.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
  ]),
);


// --- 4. box_animated_skeleton -------------------------------------
export const FIXTURE_3_SKELETON = skeletonExpect(
  4, 4, 222,
  <i32[]>[-1, 0, 1, -1],
  <string[]>["node_0", "node_1", "node_2"],
  <f32[][]>[
    <f32[]>[0, 0, 0, -0, -0, -0, -1, 1, 1, 1],
    <f32[]>[0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
  ],
);
export const FIXTURE_3_ANIMATION = animationExpect(
  "animation_0", <f32>3.70832992, 4, 4,
  4, 1, 388,
  series(10, 4, [
    key(0, <f32>0.0, 0, 0, 0, <f32[]>[0, 0, 0]),
    key(4, <f32>0.337078929, 0, 16650, 0, <f32[]>[0, 2.51953125, 0]),
  ]),
  series(10, 2, [
    key(0, <f32>0.0, 65531, 65533, 32766, <f32[]>[-2.15768814e-05, -2.15768814e-05, -2.15768814e-05, 1]),
    key(4, <f32>0.99999994, 65531, 65533, 32766, <f32[]>[-2.15768814e-05, -2.15768814e-05, -2.15768814e-05, 1]),
  ]),
  series(8, 2, [
    key(0, <f32>0.0, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
    key(4, <f32>0.99999994, 15360, 15360, 15360, <f32[]>[1, 1, 1]),
  ]),
);


/** The four fixture pairs, in the order this file emits them. */
export function fixturePairs(): FixturePair[] {
  const out = new Array<FixturePair>(4);
  out[0] = pair("skeleton_v2_le + animation_v7_le (67 joints, 68 slots)", "skeleton_v2_le", "animation_v7_le", FIXTURE_0_SKELETON, FIXTURE_0_ANIMATION);
  out[1] = pair("robot_skeleton + robot_animation (18 joints, 20 slots)", "robot_skeleton", "robot_animation", FIXTURE_1_SKELETON, FIXTURE_1_ANIMATION);
  out[2] = pair("rigged_simple_skeleton + rigged_simple_animation_0 (2 joints, 4 slots)", "rigged_simple_skeleton", "rigged_simple_animation_0", FIXTURE_2_SKELETON, FIXTURE_2_ANIMATION);
  out[3] = pair("box_animated_skeleton + box_animated_animation_0 (4 joints, 4 slots)", "box_animated_skeleton", "box_animated_animation_0", FIXTURE_3_SKELETON, FIXTURE_3_ANIMATION);
  return out;
}
