#!/usr/bin/env python3
"""Turn the vendored .ozz fixtures into the TS data module the guest compiles in.

AssemblyScript 0.28 has no `includeBytes` and no way to embed a file, so a
fixture the guest is to parse has to arrive as source. This writes that source:
one hex literal per fixture, plus its byte length and an FNV-1a hash, which the
test checks before parsing (so a corrupted literal fails loudly at the fixture,
not somewhere inside the parser).

The .ozz files under fixtures/ozz/ stay the canonical artifact; this module is
derived from them and is regenerated when they change:

    python3 tests/gen-ozz-fixtures.py

Run from the framework root. The output is committed, because the test build
compiles it and must not depend on this script having run.
"""

import hashlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
FIXTURES = HERE / "fixtures" / "ozz"
OUT = HERE / "ozz-fixture-data.ts"

# The vendored files, in the order the generated module lists them.
NAMES = [
    "skeleton_v2_le",
    "animation_v7_le",
    "robot_skeleton",
    "robot_animation",
    "rigged_simple_skeleton",
    "rigged_simple_animation_0",
    "box_animated_skeleton",
    "box_animated_animation_0",
    "skeleton_v1_le",
    "animation_v6_le",
    "skeleton_v2_be",
]


def fnv1a32(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def const_name(name: str) -> str:
    return name.upper()


def main() -> int:
    lines = [
        "// Generated by tests/gen-ozz-fixtures.py from tests/fixtures/ozz/*.ozz — do not edit.",
        "//",
        "// A fixture as source: AssemblyScript 0.28 cannot embed a file, so each archive",
        "// is carried as hex. `ozz-fixtures.ts` decodes it and checks the length and hash",
        "// below before the parser ever sees a byte.",
        "//",
        "// The .ozz files, their provenance and their licence are in fixtures/ozz/CREDITS.md.",
        "",
    ]
    total = 0
    for name in NAMES:
        path = FIXTURES / f"{name}.ozz"
        if not path.is_file():
            print(f"gen-ozz-fixtures.py: missing {path}", file=sys.stderr)
            return 1
        data = path.read_bytes()
        total += len(data)
        c = const_name(name)
        lines.append(f"/** {name}.ozz — {len(data)} bytes, {len(data) * 2} hex chars. */")
        lines.append(f'export const {c}_HEX: string = "{data.hex()}";')
        lines.append(f"export const {c}_LEN: i32 = {len(data)};")
        lines.append(f"export const {c}_FNV: u32 = 0x{fnv1a32(data):08x};")
        lines.append("")
    lines.append(f"// {len(NAMES)} fixtures, {total} bytes.")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"==> wrote {OUT} ({OUT.stat().st_size} bytes; {len(NAMES)} fixtures, {total} bytes of data)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
